// Copyright (c) 2026 Andres Chavez Ramirez. All rights reserved.
//
// End-to-end browser verification of the PHOTOGRAPH redaction path.
//
// Everything else in the suite proves one link of this chain in isolation:
//   - redaction-output.test.ts        proves the painter and the encoders
//   - imagePhotoRedaction.test.ts     proves words -> positioned rects
//   - test:offline-ocr                proves Tesseract recognises text offline
//
// None of those prove the links are connected. This file runs the whole chain
// in a real Chromium with real Tesseract on a real rendered photograph:
//
//   fixture PNG -> IndexedDB -> popup -> service worker -> offscreen document
//               -> loadImagePage -> Tesseract OCR -> local detectors
//               -> pixel rects -> black boxes -> flattened PNG
//               -> chrome.downloads -> file on disk -> pixel inspection
//
// The final assertion is the one that matters: the sensitive values are
// physically gone from the pixels of the delivered file, and the rest of the
// document is untouched.
//
// Fixtures are synthetic (RFC 2606 .test domain, never-issued SSN, documented
// test card number) and are regenerated by scripts/make-photo-fixtures.mjs.
//
// Run: npm run build && node tests/image-photo-e2e.browser.test.mjs
import { chromium } from '@playwright/test';
import { readFileSync, existsSync, readdirSync, rmSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Bounded recursive file search, used only to explain a missing download. */
function findFiles(root, depth) {
  if (!existsSync(root) || depth < 0) return [];
  const out = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = join(root, entry.name);
    if (entry.isDirectory()) out.push(...findFiles(full, depth - 1));
    else out.push(full);
  }
  return out;
}

const here = dirname(fileURLToPath(import.meta.url));
const ext = resolve(here, '..', 'dist');
const fixtures = join(here, 'fixtures');
const WORK = join(here, '..', '.tmp-photo-e2e');
const downloadDir = join(WORK, 'downloads');

const failures = [];
const notes = [];
const fail = (msg) => failures.push(msg);
const pass = (msg) => console.log(`  [ok]   ${msg}`);

if (!existsSync(join(ext, 'manifest.json'))) {
  console.error('dist/ not found - run `npm run build` first.');
  process.exit(1);
}
for (const f of ['photo-pii.png', 'photo-ordinary.png', 'photo-pii.regions.json']) {
  if (!existsSync(join(fixtures, f))) {
    console.error(`missing fixture ${f} - run \`node scripts/make-photo-fixtures.mjs\` first.`);
    process.exit(1);
  }
}

const regions = JSON.parse(readFileSync(join(fixtures, 'photo-pii.regions.json'), 'utf8'));
rmSync(WORK, { recursive: true, force: true });
mkdirSync(downloadDir, { recursive: true });

const context = await chromium.launchPersistentContext(join(WORK, 'profile'), {
  headless: false,
  // Playwright installs a browser-level download policy that routes every
  // download - including ones started through the chrome.downloads API from the
  // service worker - into downloadsPath. That is what lets the artifact be
  // inspected, because the extension calls chrome.downloads with saveAs:true
  // and would otherwise block on a native Save As dialog.
  acceptDownloads: true,
  downloadsPath: downloadDir,
  args: [
    `--disable-extensions-except=${ext}`,
    `--load-extension=${ext}`,
    '--no-first-run',
    '--no-default-browser-check'
  ]
});

try {
  const worker = context.serviceWorkers()[0] ?? (await context.waitForEvent('serviceworker', { timeout: 30000 }));
  const extensionId = new URL(worker.url()).host;
  console.log(`extension id: ${extensionId}`);

  const swProblems = [];
  worker.on('console', (m) => {
    if (m.type() === 'error') swProblems.push(m.text());
    if (m.type() === 'warning' && m.text().includes('governworld')) console.log(`  [sw] ${m.text()}`);
  });

  // The product promise is that document content never leaves the device. Assert
  // it rather than trusting it: any request to a non-local origin during the
  // whole run is a failure.
  const offDeviceRequests = [];
  context.on('request', (req) => {
    const url = req.url();
    if (/^(chrome-extension|about|data|blob|devtools):/.test(url)) return;
    if (/^(http:\/\/)?(localhost|127\.0\.0\.1)(:|\/|$)/.test(url)) return;
    offDeviceRequests.push(`${req.method()} ${url}`);
  });

  // The redaction output is produced by chrome.downloads with saveAs:true, which
  // means "ask the user where to put it". A native dialog cannot be satisfied by
  // automation, and chrome.downloads.download resolves with a download id before
  // anything is written - so without an explicit policy the artifact silently
  // never lands. A browser-level download behaviour is the supported way to
  // auto-accept it.
  //
  // Two non-obvious details, both established empirically:
  //  - the CDP session must come from a Page, not from the service worker;
  //  - the page that carries the policy must stay OPEN. Closing it drops the
  //    policy and every subsequent download is interrupted with
  //    FILE_ACCESS_DENIED against the OS Downloads folder.
  mkdirSync(downloadDir, { recursive: true });
  const policyPage = await context.newPage();
  const cdp = await policyPage.context().newCDPSession(policyPage);
  await cdp.send('Browser.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: downloadDir,
    eventsEnabled: true
  });
  let downloadReports = 0;
  cdp.on('Browser.downloadProgress', (e) => {
    if (e.state !== 'inProgress') {
      downloadReports++;
      console.log(`  [download] ${e.state} (${e.totalBytes} bytes)`);
    }
  });
  pass('download behaviour configured (saveAs dialog auto-accepted)');
  void policyPage; // intentionally kept open for the whole run

  // Drive the real popup -> worker protocol from an extension page. The worker
  // cannot message itself, and the result arrives as a broadcast that only an
  // extension page's onMessage listener receives.
  const popup = await context.newPage();
  const pageErrors = [];
  popup.on('pageerror', (e) => pageErrors.push(String(e)));
  popup.on('console', (m) => {
    if (m.type() === 'error') pageErrors.push(m.text());
    if (m.text().startsWith('TRACE')) console.log(`  ${m.text()}`);
  });
  await popup.goto(`chrome-extension://${extensionId}/popup.html`, { waitUntil: 'load' });
  // Trace every worker broadcast so a hang is diagnosable from the log.
  await popup.evaluate(() => {
    chrome.runtime.onMessage.addListener((msg) => {
      if (msg && typeof msg.type === 'string' && msg.type.startsWith('POPUP_')) {
        console.log(`TRACE ${msg.type} req=${msg.requestId}`);
      }
    });
  });
  // The install-time staged-file purge races the first write in a fresh
  // profile, so let the extension finish loading before staging.
  await popup.waitForTimeout(3000);

  /** Stage a fixture into the extension's IndexedDB and run the real preview. */
  async function processPhoto(fixtureName) {
    const b64 = readFileSync(join(fixtures, fixtureName)).toString('base64');
    // The message schema only accepts /^[A-Za-z0-9_-]{1,64}$/ for a fileKey,
    // so the staging key is a slug and the display name carries the extension.
    const fileKey = `e2e-${fixtureName.replace(/\.[a-z0-9]+$/i, '')}`;

    return await popup.evaluate(
      async ({ b64, fileKey, name }) => {
        const bin = atob(b64);
        const bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);

        // Stage into the same store the service worker reads, then prove the
        // bytes are actually durable before asking for a preview.
        let stored = 0;
        for (let attempt = 0; attempt < 10 && stored === 0; attempt++) {
          const db = await new Promise((resolve, reject) => {
            const req = indexedDB.open('governworld-redaction', 1);
            req.onupgradeneeded = () => {
              if (!req.result.objectStoreNames.contains('docfiles')) req.result.createObjectStore('docfiles');
            };
            req.onsuccess = () => resolve(req.result);
            req.onerror = () => reject(req.error);
          });
          await new Promise((resolve, reject) => {
            const tx = db.transaction('docfiles', 'readwrite');
            tx.objectStore('docfiles').put(bytes.buffer, fileKey);
            tx.oncomplete = () => resolve();
            tx.onerror = () => reject(tx.error);
          });
          const readBack = await new Promise((resolve) => {
            const tx = db.transaction('docfiles', 'readonly');
            const req = tx.objectStore('docfiles').get(fileKey);
            req.onsuccess = () => resolve(req.result?.byteLength ?? 0);
            req.onerror = () => resolve(0);
          });
          stored = readBack;
          if (stored === 0) await new Promise((r) => setTimeout(r, 500));
        }
        if (stored === 0) throw new Error('could not stage the fixture in IndexedDB');

        // The worker broadcasts POPUP_DOC_STATE / POPUP_DOC_ERROR; note that
        // `pages` is a top-level field on the message, not nested under `state`.
        return await new Promise(async (resolve, reject) => {
          const timer = setTimeout(() => reject(new Error('preview timed out after 180s')), 180000);
          const listener = (msg) => {
            if (msg?.requestId !== 'photo-e2e') return;
            if (msg.type === 'POPUP_DOC_STATE') {
              clearTimeout(timer);
              chrome.runtime.onMessage.removeListener(listener);
              resolve({ docId: msg.docId, pages: msg.pages ?? [] });
            } else if (msg.type === 'POPUP_DOC_ERROR') {
              clearTimeout(timer);
              chrome.runtime.onMessage.removeListener(listener);
              reject(new Error(`${msg.code}: ${msg.userMessage}`));
            }
          };
          chrome.runtime.onMessage.addListener(listener);
          const ack = await chrome.runtime
            .sendMessage({
              type: 'POPUP_DOC_PREVIEW',
              requestId: 'photo-e2e',
              fileKey,
              name,
              mimeType: 'image/png',
              kind: 'image'
            })
            .catch((e) => ({ ok: false, error: `sendMessage threw: ${e.message}` }));
          console.log(`ACK ${JSON.stringify(ack)}`);
          if (ack && ack.ok === false) {
            clearTimeout(timer);
            chrome.runtime.onMessage.removeListener(listener);
            reject(new Error(`worker refused the request: ${ack.error}`));
          }
        });
      },
      { b64, fileKey, name: fixtureName }
    );
  }

  /** Ask the worker to redact, then wait for the artifact to land on disk. */
  async function redact({ docId, fileKey }, fixtureName, findingIds) {
    const done = await popup.evaluate(
      async ({ fileKey, docId, name, findingIds }) => {
        // The worker derives the rectangles from the session's own preview
        // pages and validates every id, so `boxes` is intentionally empty.
        const result = await new Promise(async (resolve, reject) => {
          const timer = setTimeout(() => reject(new Error('redact timed out after 180s')), 180000);
          const listener = (msg) => {
            if (msg?.requestId !== 'photo-e2e') return;
            if (msg.type === 'POPUP_DOC_DONE') {
              clearTimeout(timer);
              chrome.runtime.onMessage.removeListener(listener);
              resolve({ outputName: msg.outputName, hadInlineBytes: typeof msg.outputBytesBase64 === 'string' });
            } else if (msg.type === 'POPUP_DOC_ERROR') {
              clearTimeout(timer);
              chrome.runtime.onMessage.removeListener(listener);
              reject(new Error(`${msg.code}: ${msg.userMessage}`));
            }
          };
          chrome.runtime.onMessage.addListener(listener);
          const ack = await chrome.runtime
            .sendMessage({
              type: 'POPUP_DOC_REDACT',
              requestId: 'photo-e2e',
              docId,
              fileKey,
              name,
              mimeType: 'image/png',
              kind: 'image',
              boxes: [],
              findingIds
            })
            .catch((e) => ({ ok: false, error: `sendMessage threw: ${e.message}` }));
          if (ack && ack.ok === false) {
            clearTimeout(timer);
            chrome.runtime.onMessage.removeListener(listener);
            reject(new Error(`worker refused the request: ${ack.error}`));
          }
        });
        return result;
      },
      { fileKey, docId, name: fixtureName, findingIds }
    );
    console.log(`  worker reported output "${done.outputName}", inline-bytes-fallback=${done.hadInlineBytes}`);

    const deadline = Date.now() + 30000;
    while (Date.now() < deadline) {
      const done2 = readdirSync(downloadDir).filter((f) => f.endsWith('.png'));
      if (done2.length > 0) {
        const full = join(downloadDir, done2[0]);
        if (existsSync(full) && readFileSync(full).length > 0) return { path: full, name: done2[0] };
      }
      await new Promise((r) => setTimeout(r, 250));
    }
    // Nothing landed: report where Chrome actually put it so the failure is
    // actionable instead of just "no file".
    console.log(`  searching for ${done.outputName} ...`);
    for (const root of [WORK, join(WORK, 'profile')]) {
      const hits = findFiles(root, 6).filter((p) => p.endsWith('.png') || p.includes('redacted'));
      if (hits.length) console.log(`  under ${root}: ${hits.slice(0, 10).join(' | ')}`);
    }
    console.log(`  default downloads: ${[...findFiles(join(homedir(), 'Downloads'), 2)].join(' | ') || '(empty)'}`);
    return null;
  }

  /** Decode two PNGs in a page and measure region luminance before/after. */
  async function comparePixels(originalPath, redactedPath) {
    const page = await context.newPage();
    await page.goto('about:blank');
    const report = await page.evaluate(
      async ({ originalB64, redactedB64, regions }) => {
        async function toImageData(b64) {
          const bin = atob(b64);
          const bytes = new Uint8Array(bin.length);
          for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
          const bmp = await createImageBitmap(new Blob([bytes], { type: 'image/png' }));
          const c = document.createElement('canvas');
          c.width = bmp.width;
          c.height = bmp.height;
          const ctx = c.getContext('2d', { willReadFrequently: true });
          ctx.drawImage(bmp, 0, 0);
          const data = ctx.getImageData(0, 0, c.width, c.height).data;
          bmp.close();
          return { width: c.width, height: c.height, data };
        }
        const orig = await toImageData(originalB64);
        const red = await toImageData(redactedB64);

        function stats(img, r) {
          let sum = 0;
          let n = 0;
          let dark = 0;
          for (let y = Math.max(0, r.y); y < Math.min(r.y + r.height, img.height); y++) {
            for (let x = Math.max(0, r.x); x < Math.min(r.x + r.width, img.width); x++) {
              const i = (y * img.width + x) * 4;
              const lum = 0.2126 * img.data[i] + 0.7152 * img.data[i + 1] + 0.0722 * img.data[i + 2];
              sum += lum;
              n++;
              if (lum < 40) dark++;
            }
          }
          return { meanLum: n ? sum / n : 0, darkFraction: n ? dark / n : 0 };
        }

        return {
          sameSize: orig.width === red.width && orig.height === red.height,
          redactedSize: { w: red.width, h: red.height },
          originalSize: { w: orig.width, h: orig.height },
          sensitive: regions.regions.map((r) => ({
            label: r.label,
            category: r.category,
            text: r.text,
            before: stats(orig, r),
            after: stats(red, r)
          })),
          untouched: regions.mustRemainUnchanged.map((r) => ({
            label: r.label,
            before: stats(orig, r),
            after: stats(red, r)
          }))
        };
      },
      {
        originalB64: readFileSync(originalPath).toString('base64'),
        redactedB64: readFileSync(redactedPath).toString('base64'),
        regions
      }
    );
    await page.close();
    return report;
  }

  // ------------------------------------------------------------------ case 1
  console.log('\nPII photograph: OCR -> detect -> redact -> download');
  const pii = await processPhoto('photo-pii.png');
  const piiFindings = pii.pages.flatMap((p) => p.findings ?? []);
  const piiCategories = [...new Set(piiFindings.map((f) => f.category))];
  console.log(`  pages=${pii.pages.length} findings=${piiFindings.length} categories=[${piiCategories.join(', ')}]`);

  // DETECTED
  if (piiFindings.length === 0) {
    fail('DETECTED: OCR + detection produced no findings on the PII photograph');
  } else {
    pass(`DETECTED ${piiFindings.length} findings across ${piiCategories.length} categories`);
  }
  for (const expected of regions.regions) {
    if (piiCategories.includes(expected.category)) {
      pass(`DETECTED expected category ${expected.category} ("${expected.text}")`);
    } else {
      fail(`DETECTED missing ${expected.category} ("${expected.text}") - OCR may have misread it`);
    }
  }
  if (piiFindings.length < regions.regions.length) {
    notes.push(
      `OCR read ${piiFindings.length} of ${regions.regions.length} synthetic values; missing: ` +
        regions.regions.filter((r) => !piiCategories.includes(r.category)).map((r) => r.text).join(', ')
    );
  }

  const withRects = piiFindings.filter((f) => Array.isArray(f.rects) && f.rects.length > 0);
  if (withRects.length === 0) {
    fail('REDACTED: findings carried no rectangles, so nothing could be painted');
  } else {
    pass(`mapped ${withRects.reduce((n, f) => n + f.rects.length, 0)} rectangles from ${withRects.length} findings`);
  }

  const piiDownload = await redact(
    { docId: pii.docId, fileKey: 'e2e-photo-pii' },
    'photo-pii.png',
    piiFindings.map((f) => f.id)
  );
  if (!piiDownload) {
    fail('REDACTED: no PNG was delivered to disk');
  } else {
    pass(`REDACTED delivered ${piiDownload.name} (${readFileSync(piiDownload.path).length} bytes)`);
  }

  // VERIFIED
  if (piiDownload) {
    const pixels = await comparePixels(join(fixtures, 'photo-pii.png'), piiDownload.path);
    console.log(
      `  original ${pixels.originalSize.w}x${pixels.originalSize.h} -> redacted ${pixels.redactedSize.w}x${pixels.redactedSize.h}`
    );
    if (!pixels.sameSize) fail('VERIFIED: redacted dimensions differ from the source image');

    for (const s of pixels.sensitive) {
      const redacted = s.after.darkFraction > 0.85 && s.after.meanLum < s.before.meanLum - 20;
      if (redacted) {
        pass(
          `VERIFIED ${s.label}: ${(s.after.darkFraction * 100).toFixed(1)}% dark (was ${(s.before.darkFraction * 100).toFixed(1)}%), ` +
            `meanLum ${s.before.meanLum.toFixed(0)} -> ${s.after.meanLum.toFixed(0)}`
        );
      } else {
        fail(
          `VERIFIED ${s.label}: NOT redacted - darkFraction=${s.after.darkFraction.toFixed(3)} ` +
            `meanLum ${s.before.meanLum.toFixed(1)} -> ${s.after.meanLum.toFixed(1)}`
        );
      }
    }
    for (const u of pixels.untouched) {
      const delta = Math.abs(u.after.meanLum - u.before.meanLum);
      if (delta < 12) {
        pass(`VERIFIED ${u.label}: unchanged (meanLum delta ${delta.toFixed(2)})`);
      } else {
        fail(`VERIFIED ${u.label}: collateral change, meanLum ${u.before.meanLum.toFixed(1)} -> ${u.after.meanLum.toFixed(1)}`);
      }
    }
  }

  // ------------------------------------------------------------------ case 2
  console.log('\nordinary photograph: no false positives');
  rmSync(downloadDir, { recursive: true, force: true });
  mkdirSync(downloadDir, { recursive: true });
  const ordinary = await processPhoto('photo-ordinary.png');
  const ordinaryFindings = ordinary.pages.flatMap((p) => p.findings ?? []);
  console.log(`  pages=${ordinary.pages.length} findings=${ordinaryFindings.length}`);
  if (ordinaryFindings.length === 0) {
    pass('no findings on prose with no sensitive values - no unnecessary redaction');
  } else {
    const cats = [...new Set(ordinaryFindings.map((f) => f.category))];
    fail(`false positives on an ordinary photograph: [${cats.join(', ')}] (${ordinaryFindings.length} findings)`);
  }

  // ---------------------------------------------------------------- hygiene
  console.log('\nprivacy + stability');
  if (offDeviceRequests.length === 0) {
    pass('no request left the device - document content stayed local');
  } else {
    for (const r of offDeviceRequests) fail(`off-device request: ${r}`);
  }

  const irrelevant = [...swProblems, ...pageErrors].filter(
    (t) => !/favicon|net::ERR_FILE_NOT_FOUND|Download the React DevTools/i.test(t)
  );
  if (irrelevant.length === 0) {
    pass('no service-worker or page console errors');
  } else {
    for (const e of irrelevant) fail(`console error: ${e}`);
  }
} finally {
  await context.close();
  rmSync(WORK, { recursive: true, force: true });
}

console.log('');
if (notes.length) {
  console.log('NOTES:');
  for (const n of notes) console.log(`  - ${n}`);
}
if (failures.length) {
  console.error('PHOTO E2E FAILED:');
  for (const f of failures) console.error(`  - ${f}`);
  process.exit(1);
}
console.log('PHOTO E2E PASSED: OCR, detection, coordinate mapping, pixel redaction, and artifact delivery verified in Chromium.');
