// Housekeeping for release artefacts and test scratch output.
//
// The release directory accumulated one 14 MB archive pair per packaging
// iteration. Fourteen iterations later it held 19 archives and 273 MB, and the
// only thing distinguishing the current one from the rest was the commit SHA in
// the filename. That is a trap: several of those are explicitly marked
// do-not-submit in RELEASE_EVIDENCE.md, and the wrong one being uploaded to the
// Chrome Web Store is not a recoverable mistake for a first listing.
//
// This script keeps exactly the current artefact pair and removes the rest. It
// is deliberately conservative:
//
//   - The current pair is identified from the commit recorded in
//     RELEASE_EVIDENCE.md, not from a glob, so a stale archive is never guessed
//     at.
//   - Every archive is named `<prefix>-<sha>.<ext>`; anything that does not
//     parse is left alone and reported, never deleted on a guess.
//   - Nothing is deleted unless the corresponding commit is still in the
//     repository, so an archive is only removed when it is reproducible.
//   - Test scratch directories are removed; both are regenerated by their
//     scripts on demand.
//
//   node scripts/housekeeping.mjs            # report, delete nothing
//   node scripts/housekeeping.mjs --apply    # perform the deletions
//
// A dry run is the default because this deletes files.

import { existsSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const root = process.cwd();
const releaseDir = join(root, "release");
const apply = process.argv.includes("--apply");

/** Scratch directories produced by test scripts; safe to remove. */
const SCRATCH = [".tmp-ui-session", ".tmp-ocr-smoke"];

const currentSha = (() => {
  const evidence = readFileSync(join(root, "RELEASE_EVIDENCE.md"), "utf8");
  const m = evidence.match(/\|\s*Commit SHA\s*\|\s*`([0-9a-f]{7,40})`/);
  return m ? m[1] : null;
})();

const gitHas = (sha) => {
  try {
    execFileSync("git", ["cat-file", "-e", `${sha}^{commit}`], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
};

const sizeOf = (p) => {
  try {
    return statSync(p).size;
  } catch {
    return 0;
  }
};

const dirSize = (p) => {
  let total = 0;
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const full = join(d, e.name);
      if (e.isDirectory()) walk(full);
      else total += sizeOf(full);
    }
  };
  try {
    walk(p);
  } catch {
    /* absent */
  }
  return total;
};

let freed = 0;
const actions = [];

if (!existsSync(releaseDir)) {
  console.log("no release/ directory; nothing to do");
  process.exit(0);
}

if (!currentSha) {
  console.error("could not read the current commit SHA from RELEASE_EVIDENCE.md; refusing to guess");
  process.exit(1);
}
console.log(`current release commit: ${currentSha}\n`);

for (const name of readdirSync(releaseDir)) {
  const m = name.match(/^governworld-redaction-([0-9a-f]{7,40})\.(zip|tar\.gz)$/);
  if (!m) continue; // unrecognised name: leave it alone
  const [, sha] = m;
  if (sha === currentSha) continue; // this is the one to keep

  const full = join(releaseDir, name);
  const size = sizeOf(full);
  if (!gitHas(sha)) {
    actions.push({ kind: "KEEP", what: name, size, why: "commit is not in this repository" });
    continue;
  }
  actions.push({
    kind: "DELETE",
    what: name,
    size,
    why: `superseded by ${currentSha}; rebuild with npm run release:zip ${sha}`,
  });
  freed += size;
  if (apply) rmSync(full, { force: true });
}

for (const d of SCRATCH) {
  const full = join(root, d);
  if (!existsSync(full)) continue;
  const size = dirSize(full);
  actions.push({ kind: "DELETE", what: `${d}/`, size, why: "regenerated by its test script" });
  freed += size;
  if (apply) rmSync(full, { recursive: true, force: true });
}

for (const a of actions) {
  const mb = `${(a.size / 1024 / 1024).toFixed(1)} MB`;
  console.log(`  ${a.kind.padEnd(6)} ${a.what.padEnd(46)} ${mb.padStart(9)}  (${a.why})`);
}

if (actions.length === 0) {
  console.log("\nnothing to clean: only the current release and the store assets remain");
} else {
  console.log(
    `\n${(freed / 1024 / 1024).toFixed(0)} MB ${apply ? "reclaimed" : "reclaimable"}${
      apply ? "" : " - re-run with --apply"
    }`,
  );
}
